import type { Metadata } from "next";
import "./globals.css";
// const Satoshi = SatoshiFont({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Novice",
  description: "Generated by create next app",
  // favicon
  icons: {
    icon: "./assets/icons/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
