import type { Metadata } from "next";
// import { Satoshi as SatoshiFont } from "next/font/google"; // Rename the imported constant
import "./globals.css";

// const Satoshi = SatoshiFont({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
